In [1]:
import numpy as np

In [56]:
# part1 >>> dataset

# X = (hours sleeping, hours studying), y = Score on test
X = np.array(([3,5], [5,1], [10,2]), dtype=float)
y = np.array(([75], [82], [93]), dtype=float)

In [57]:
X.shape

(3, 2)

In [58]:
y.shape

(3, 1)

In [59]:
X

array([[  3.,   5.],
       [  5.,   1.],
       [ 10.,   2.]])

In [60]:
y

array([[ 75.],
       [ 82.],
       [ 93.]])

In [63]:
# apply data scaling
# i will use min max scaler
for i in range(X.shape[1]):
    xmax=np.max(X[:,i])
    xmin=np.min(X[:,i])
    for j in range(X.shape[0]):
        X[j][i]=(X[j][i]-xmin)/(xmax-xmin)
miny=np.min(y)
maxy=np.max(y)
y=(y-miny)/(maxy-miny)

In [64]:
X

array([[ 0.        ,  1.        ],
       [ 0.28571429,  0.        ],
       [ 1.        ,  0.25      ]])

In [65]:
y

array([[ 0.        ],
       [ 0.38888889],
       [ 1.        ]])

In [117]:
class ANN:
    def __init__(self,inlayer_size,outlayer_size,hidden_layers_dict):
        self.inlayer_size=inlayer_size
        self.outlayer_size=outlayer_size
        self.hidden_layers_dict=hidden_layers_dict
        self.W1 = np.random.randn(self.inlayer_size, self.hidden_layers_dict['H1'])
        self.W2 = np.random.randn(self.hidden_layers_dict['H1'], self.outlayer_size)
        
    @staticmethod
    def sigmoid(z):
        # apply sigmoid function to every cell of matrix z
        return 1/(1+np.exp(-z))
    
    @staticmethod
    def mse_loss(y,yhat):
        return (1/2)*np.sum(np.square(y-yhat))
    
    def forward(self,x):
        self.z2=np.dot(x,self.W1)
        self.a2=ANN.sigmoid(self.z2)
        self.z3=np.dot(self.a2,self.W2)
        yhat=ANN.sigmoid(self.z3)
        return yhat

In [123]:
model=ANN(inlayer_size=2,outlayer_size=1,hidden_layers_dict={'H1':3})

In [124]:
ypred=model.forward(X)

In [125]:
y

array([[ 0.        ],
       [ 0.38888889],
       [ 1.        ]])

In [126]:
ypred

array([[ 0.3915798 ],
       [ 0.38752916],
       [ 0.43147535]])

In [127]:
ANN.mse_loss(y,ypred)

0.23827843122284526